version: 2
updates:
  # CLI updates
  - package-ecosystem: 'npm'
    directory: '/'
    commit-message:
      prefix: 'chore'
    labels:
      - '📦 dependencies'
    schedule:
      interval: 'monthly'
    groups:
      cli-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'ci'
    schedule:
      interval: 'monthly'
    labels:
      - '📦 dependencies'
      - '🤖 ci/cd'
    groups:
      github-actions:
        patterns:
          - '*'
  # Template updates
  - package-ecosystem: 'npm'
    directories:
      - '/src/dependencies/**/*'
    commit-message:
      prefix: 'fix'
    labels:
      - '📦 dependencies'
    schedule:
      interval: 'monthly'
      day: 'monday'
    groups:
      template-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
